version: '3.8'

services:
  app:
    build:
      context: ../build/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: pnpm run dev 
  internal-token-service:
    build:
      context: ../build
      dockerfile: internal-token-server.Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped 