version: '3.8'

services:
  app:
    build:
      context: ../build/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped 
  internal-token-service:
    build:
      context: ../build
      dockerfile: internal-token-server.Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped 